---
name: Reactor
version: 0.0.1
slug: reactor
description: An automation engine that integrates rules and actions
arch:
    - amd64
    - i386
image: toggledbits/reactor:latest-{arch}
init: false
url: https://github.com/mrw298/hassio-reactor-addon
startup: application
boot: auto
homeassistant_api: true
ingress: true
