---
name: Reactor
version: 0.0.1
slug: reactor
description: An automation engine that integrates rules and actions
arch:
  - amd64
#  - i386
image: mrw298/toggledbits-reactor-{arch}
init: false
url: https://github.com/mrw298/hassio-reactor-addon/tree/master/reactor
startup: application
boot: auto
homeassistant_api: true
ingress: true
map:
  - config:rw
ports:
  "8111/tcp": 8111
ports_description:
  "8111": "Port for reactor"
