name: Build Images

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
       
  build:
    name: Build ${{ matrix.arch }} image
    strategy:
      matrix:
        arch: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.3.0
     
     